name: 🐛 Bug report
description: Report an issue or problem with the way Orebfuscator is functioning.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Before going any further, please check our [common issues](https://github.com/Imprex-Development/Orebfuscator/wiki/Common-Issues) page and make sure you're using the [latest version](https://github.com/Imprex-Development/Orebfuscator/releases/latest)."
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a short description of the issue in the space below.
      placeholder: Description goes here!
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Please provide a clear list of steps we should follow in order to reproduce your issue in the space below.
      placeholder: List reproduction steps here, please!
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Please provide a description of what you expected to happen.
      placeholder: Describe what you expected to happen here.
    validations:
      required: true
  - type: textarea
    id: dump
    attributes:
      label: Orebfuscator Dump
      description: Please provide an Orebfuscator dump file (use `/orebfuscator dump`) or if Orebfuscator didn't start provide a ProtocolLib dump (use `/protocol dump`). You should use https://gist.github.com/ to upload, then include the link below.
      placeholder: https://gist.github.com/HelpfulBugReporter/ThisIsAVeryUsefulLogOutput
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Details
      description: Please include any other relevant details in the space below.
      placeholder: I was able to reproduce this only at the end of a rainbow.
    validations:
      required: false
